version: '3.8'

services:
  coding-ai-agent:
    build:
      context: .
      dockerfile: docker/Dockerfile.dev
    container_name: coding-ai-agent-dev
    ports:
      - "8002:8002"
    volumes:
      - .:/app
      - /var/run/docker.sock:/var/run/docker.sock
      - coding-workspaces:/tmp/coding-agent-workspaces
    environment:
      - ENVIRONMENT=development
      - LOG_LEVEL=DEBUG
      - API_HOST=0.0.0.0
      - API_PORT=8002
    env_file:
      - .env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8002/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - coding-network

  # Optional: Add a simple code editor for development
  code-server:
    image: codercom/code-server:latest
    container_name: coding-ai-agent-editor
    ports:
      - "8080:8080"
    volumes:
      - .:/home/coder/project
      - coding-workspaces:/tmp/coding-agent-workspaces
    environment:
      - PASSWORD=coding-agent-dev
    command: --bind-addr 0.0.0.0:8080 --auth password /home/coder/project
    networks:
      - coding-network
    profiles:
      - editor

volumes:
  coding-workspaces:
    driver: local

networks:
  coding-network:
    driver: bridge